### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by jakubszalek** [brkclw/shine-bright-like-a-react#17]
Hello Maciej!

Thank you for taking the time to complete our test and to agree to provide some improvements.

It is a fundamental part of the interview process. There are no time constraints from my side, so that you can provide fixes and discussion on your own time, at your own pace.

Cheers,
Kuba

**Comment by brkclw** [comment]
Hi!

All improvements are ready to test. Please let me know if you have any questions.
