### ISSUE TITLE
Nice-to-have tasks

### ISSUE THREAD

**Issue by jakubszalek** [brkclw/shine-bright-like-a-react#18]
Maciej, I saw that you put a lot of effort in the test task already but I have to ask you for some additional work.

I'd love to see your implementation of at least one of our nice-to-have tasks: pagination and/or search which fetches data from GH api - it will allow me to rate your skills appropriately.

PS. I saw your 'todo' notes - `search` query allows to use pagination, I've just confirmed that it is still working.

**Comment by brkclw** [comment]
Hi,
please check #25 😉
