### ISSUE TITLE
Misc. code improvements

### ISSUE THREAD

**Issue by jakubszalek** [brkclw/shine-bright-like-a-react#19]
I found some small issues in the code that should be fixed or improved:

1. Some imports of `React` are missing (e.g. src/components/repository/RepositoryList.tsx:5)
2. Test cases for `RepositoryList` are very nice described but I think that most of test cases should be kept in one test suite to avoid unnecessary rendering of the component.
3. One of `Table handlers` test case renders component when it's not needed.
4. There is no error handling for fetching the data from GH api.

One more thing regarding dev tools:
1. Running `yarn lint` returns `typescript-check: command not found`

**Comment by brkclw** [comment]
ad. 1
Since v17 you can use `JSX` without importing `React`
Please see [docs](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html)

ad. 2,3
True! Fixed in #22 

ad. 4 and dev tools
Added basic error link for Apollo and missing `yarn` for `typescript-check`. 
Done in: #23

**Comment by jakubszalek** [comment]
@brkclw Thank you for providing your changes.
Ad.1 I totally agree that using JSX doesn't require importing React anymore but you still need to import other dependencies from react lib, like `FC` or `ReactNode`. In other case you're referring to global variable which is not recommended.
