### ISSUE TITLE
Issue with Docker script

### ISSUE THREAD

**Issue by jakubszalek** [brkclw/shine-bright-like-a-react#20]
It is great to see that you added a Docker config for the test task as it's one of our nice-to-have task!
Unfortunately, I found one issue during running the app according to your docs in readme:

1. executing `build.local.sh` gives me `zsh: permission denied:` - it seems like file permission issue 

Please, let me know in a case I'm missing anything!

**Comment by brkclw** [comment]
Hi, true, execute permission was missing. Added it in #21
